// Palette aligned with the homepage (cream + lime accent + dark-green panels).
export const FIN = {
  bg: '#fafaf7',
  bg2: '#f0efe8',
  paper: '#ffffff',
  ink: '#0a0a0a',
  teal: '#1a2e1a',
  tealD: '#0f1c0f',
  ochre: '#d7ff3a',
  ochreD: '#555555',
  sand: '#eae6c8',
  stone: '#555555',
  rule: '#e5e3da',
  ruleD: 'rgba(255,255,255,0.18)',
  footer: '#1e3a2a',
  footerText: '#fafaf7',
  serif: 'var(--font-cormorant), "Cormorant Garamond", Georgia, serif',
  sans: 'var(--font-inter), "Inter", system-ui, sans-serif',
  mono: 'var(--font-mono), "JetBrains Mono", ui-monospace, monospace',
} as const;
